import "%modules%/header/header";
import "%modules%/footer/footer";
import "%modules%/intro/intro";
import "%modules%/modal/modal";
import "%modules%/cookie/cookie";
import "%modules%/form/form";
import "%modules%/animations/animation";
import "%modules%/compare-tool/compare-tool";
import "%modules%/translit/translit";
